name: Deployment pipeline


on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
    types:
      - synchronize
jobs:
  deployment_pipeline:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js 
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Frontend Dependencies
        run:  npm install

      - name: Run Frontend Lint
        run: npm run lint

      - name: build prod version for frontend
        run: npm run build

          



  # tag_release:
  #   needs: deployment_pipeline
  #   runs-on: ubuntu-20.04
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Bump version and push tag
  #     env:
  #       COMMIT_MESSAGE: ${{ toJson(github.event.commits[0].message) }}
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       DEFAULT_BUMP: patch 
  #     if: ${{ github.event_name == 'push' && !contains(env.COMMIT_MESSAGE, '#skip') }}
  #     uses: anothrNick/github-tag-action@1.67.0



