//commented filters have problems to search

const healthFilterOptions = [
  'Alcohol-Cocktail',
  'Alcohol-Free',
  'Celery-Free',
  //'Crustcean-Free',
  'Dairy-Free',
  'Egg-Free',
  //'DASH',
  'Fish-Free',
  'FODMAP-Free',
  'Gluten-Free',
  'Immuno-Supportive',
  'Keto-Friendly',
  'Kidney-Friendly',
  'Kosher',
  //'Low Potassium',
  //'Low Sugar',
  'Lupine-Free',
  //'Mediterranean',
  'Mollusk-Free	',
  'Mustard-Free',
  //'No oil added	',
  'Paleo',
  'Peanut-Free',
  'Pescatarian',
  'Pork-Free',
  'Red-Meat-Free',
  'Sesame-Free',
  'Shellfish-Free',
  'Soy-Free',
  'Sugar-Conscious',
  'Sulfite-Free',
  'Tree-Nut-Free',
  'Vegan',
  'Vegetarian',
  'Wheat-Free'
]

export default healthFilterOptions
