name: Deployment pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
    types:
      - synchronize

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js (Backend)
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Backend Dependencies
        run: npm install
        working-directory: ./backend

      - name: Run Backend Lint
        run: npm run lint
        working-directory: ./backend

      - name: Set Up Node.js (Frontend)
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Frontend Dependencies
        run: npm install
        working-directory: ./foodapp

      - name: Run Frontend Lint
        run: npm run lint
        working-directory: ./foodapp
